// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>
#include <stdlib.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"

#include "HTTP_Interface.hpp"

unsigned int microsecond           = 1000000;
const char* server_host            = "httpbin.org";
const char* server_port            = "443";
constexpr const char* http_request = "GET /get HTTP/1.1\r\n"
                                     "Host: httpbin.org\r\n"
                                     "\r\n";

int main(int argc, const char* argv[])
{
    HTTP_Interface hi = HTTP_Interface(argv[1]);

    char buf[BUFSIZ];
    int len = BUFSIZ;

    hi.e_connect(server_host, server_port);
    hi.e_request(http_request);
    hi.e_get_response(buf, len);
    hi.e_close();

    puts(buf);
    puts("[+] Response printed");

    return 0;
}