// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++) {
        if (strcmp(argv[i], "--simulate") == 0) {
            fprintf(stdout, "Running in simulation mode\n");

            (*argc)--;
            for (; i < *argc; i++) {
                argv[i] = argv[i + 1];
            }
            return true;
        }
    }
    return false;
}

void connect(){

}

void request(){
    
}

void get_response(){
    
}

void close(){
    
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret               = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv)) {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2) {
        fprintf(stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    oe_enclave_setting_context_switchless_t switchless_setting = {
        1,  // number of host worker threads
        0}; // number of enclave worker threads.
    oe_enclave_setting_t settings[] = {{
        .setting_type = OE_ENCLAVE_SETTING_CONTEXT_SWITCHLESS,
        .u.context_switchless_setting = &switchless_setting,
    }};

    // Create the enclave
    result = oe_create_helloworld_enclave(argv[1], OE_ENCLAVE_TYPE_SGX, flags, settings, OE_COUNTOF(settings), &enclave);
    if (result != OE_OK) {
        fprintf(stderr, "oe_create_helloworld_enclave(): result=%u (%s)\n", result, oe_result_str(result));
        goto exit;
    }

    result = initialize_enclave(enclave);
    if (result != OE_OK) {
        fprintf(stderr, "calling into enclave_https failed: result=%u (%s)\n", result, oe_result_str(result));
        goto exit;
    }

    result = call_test_2(enclave);
    if (result != OE_OK) {
        fprintf(stderr, "calling into enclave_https failed: result=%u (%s)\n", result, oe_result_str(result));
        goto exit;
    }

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
